title: Hogwash Cheaptalk
baseurl: http://hogwashcheaptalk.com
languageCode: en-us
theme: heather-hugo

googleAnalytics: UA-79707004-1

metaDataFormat: yaml

permalinks:
  post: /:year/:month/:title/

taxonomies:
  tag: tags
  category: categories
  menu: menu

params:
  menu:
    - about
    - writing
    - music

  tag: by Sean Maloney
  description: Writings by Sean Maloney
  author: 
    name: Sean Maloney
    email: spmaloney@gmail.com
  readMoreLabel: Read more

